### ISSUE TITLE
Compass

### ISSUE THREAD

**Issue by erichaus** [lifegadget/ember-cli-bootstrap-sassy#7]
Hello,

I am using this library with ember-cli-sass and am wondering how I can also use compass mixins?

I found this lib https://github.com/quaertym/ember-cli-compass-compiler but when I install it I get

```
$ ember serve --proxy http://localhost:8001
version: 0.1.12
Could not find watchman, falling back to NodeWatcher for file system events
bootstrap-sassy config:  all JS enabled, glphicons enabled
Proxying to http://localhost:8001
Livereload server on port 35729
Serving on http://0.0.0.0:4200/

directory tmp/compass_compiler-tmp_cache_dir-l6YHOycm.tmp/assets
    error app/styles/app.scss (Line 7: File to import not found or unreadable: bootstrap.
Load paths:
  Compass::SpriteImporter
  /Users/eric/Projects/craft/craft-frontend/app/styles
  /Library/Ruby/Gems/2.0.0/gems/compass-core-1.0.3/stylesheets)
Compilation failed in 1 files.

Command failed:
Error: Command failed:
  at ChildProcess.exithandler (child_process.js:648:15)
  at ChildProcess.emit (events.js:98:17)
  at maybeClose (child_process.js:756:16)
  at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

any information appreciated!

**Comment by yankeeinlondon** [comment]
I think the watchman issue is probably unrelated, so I'd ignore. Also it looks like, although I wouldn't swear to it, that Bootstrap has loaded successfully. I'm not familiar with the compass CLI addon so can't help much there but if you look at how the Sassy addon hooks into ember-sass-cli:

> https://github.com/lifegadget/ember-cli-bootstrap-sassy/blob/master/index.js#L21-L27

You might want to compare that to how your compass addon hooks into SASS and make sure that it's approach is non-destructive because both Bootstrap and Compass need to share the SASS resource. Hope that helps. 

If it provides any encouragement I have successfully done something similar by including both Bootstrap and Bourbon SCSS into Ember SASS/CLI environment. :)
